# Day 03 — NLP Basics

**Task:** Text Preprocessing and Text Vectorization

Today we will work with:

- NLTK / spaCy for tokenization
- Stop-word removal
- Lemmatization
- CountVectorizer
- TfidfVectorizer
- Reusable text → vector function
- Top TF-IDF terms

In [1]:
import nltk
import pandas as pd

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from preprocess import preprocess_text
from preprocess import preprocess_to_string

## 1. NLTK Tokenization

Tokenization is the process of breaking text into smaller units called tokens.

For example:

```text
"Natural language processing is powerful."

In [2]:
text = """
Natural language processing is powerful.
It helps computers understand human language.
"""

tokens = word_tokenize(text)

print(tokens)

['Natural', 'language', 'processing', 'is', 'powerful', '.', 'It', 'helps', 'computers', 'understand', 'human', 'language', '.']

## 2. Remove Stop Words

Stop words are common words that often provide limited information for NLP tasks.

Examples include:

- the
- is
- a
- an
- and
- to
- of
- in

We will remove these words from our tokens.

In [3]:
stop_words = set(stopwords.words("english"))

filtered_tokens = [
    token
    for token in tokens
    if token.lower() not in stop_words
]

print(filtered_tokens)

['Natural', 'language', 'processing', 'powerful', '.', 'helps', 'computers', 'understand', 'human', 'language', '.']

## 3. Lemmatization with NLTK

Lemmatization converts words into their base or dictionary form.

Examples:

- cars → car
- studies → study
- running → running

We will use NLTK's WordNetLemmatizer to understand the basic idea of lemmatization.

In [4]:
lemmatizer = WordNetLemmatizer()

lemmatized_tokens = [
    lemmatizer.lemmatize(token.lower())
    for token in filtered_tokens
]

print(lemmatized_tokens)

['natural', 'language', 'processing', 'powerful', '.', 'help', 'computer', 'understand', 'human', 'language', '.']

## 4. Text Preprocessing with spaCy

Now we will use our reusable `preprocess.py` utility.

The `preprocess_text()` function performs:

1. Lowercasing
2. Tokenization
3. Stop-word removal
4. Punctuation removal
5. Number removal
6. Lemmatization

This allows us to reuse the same preprocessing logic in other NLP projects.

In [5]:
text = """
Natural language processing allows computers to understand
human languages. Computers are learning from large datasets.
"""

cleaned_tokens = preprocess_text(text)

print(cleaned_tokens)

['natural', 'language', 'processing', 'allow', 'computer', 'understand', 'human', 'language', 'computer', 'learn', 'large', 'dataset']

## 5. Convert Preprocessed Tokens into Text

Machine learning vectorizers expect text documents.

Our `preprocess_to_string()` function converts the cleaned tokens back into one clean text string.

Example:

Raw text:

"Computers are learning from datasets."

Cleaned text:

"computer learn dataset"

In [6]:
cleaned_text = preprocess_to_string(text)

print(cleaned_text)

natural language processing allow computer understand human language computer learn large dataset

## 6. Create Sample Documents

We need multiple documents to demonstrate CountVectorizer and TF-IDF.

Each document represents one text example.

Our documents will contain information about:

- Natural Language Processing
- Machine Learning
- Deep Learning
- Chatbots

In [7]:
documents = [
    """
    Natural language processing helps computers understand human language.
    NLP is used in chatbots, search engines, and virtual assistants.
    """,

    """
    Machine learning allows computers to learn from data.
    Machine learning is widely used for prediction and classification.
    """,

    """
    Deep learning uses neural networks to learn complex patterns.
    Neural networks are useful for images, speech, and language processing.
    """,

    """
    Chatbots use natural language processing to understand user questions.
    Modern chatbots can generate useful responses using machine learning.
    """
]

print(f"Number of documents: {len(documents)}")

Number of documents: 4

## 7. Preprocess All Documents

We will apply our reusable preprocessing function to every document.

The result will be clean text that can be passed to the scikit-learn vectorizers.

In [8]:
cleaned_documents = [
    preprocess_to_string(document)
    for document in documents
]

for index, document in enumerate(cleaned_documents, start=1):
    print(f"Document {index}:")
    print(document)
    print()

Document 1:
natural language processing help computer understand human language nlp chatbot search engine virtual assistant

Document 2:
machine learning allow computer learn datum machine learning widely prediction classification

Document 3:
deep learning use neural network learn complex pattern neural network useful image speech language processing

Document 4:
chatbot use natural language processing understand user question modern chatbot generate useful response machine learning

## 8. CountVectorizer

`CountVectorizer` converts text documents into numerical vectors based on word frequency.

For example:

"machine learning machine"

becomes:

machine → 2

learning → 1

Each unique word becomes a feature, and the value represents how many times that word appears.

In [9]:
count_vectorizer = CountVectorizer()

count_matrix = count_vectorizer.fit_transform(
    cleaned_documents
)

print(count_matrix)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 49 stored elements and shape (4, 35)>
  Coords	Values
  (0, 18)	1
  (0, 13)	2
  (0, 24)	1
  (0, 10)	1
  (0, 5)	1
  (0, 29)	1
  (0, 11)	1
  (0, 21)	1
  (0, 2)	1
  (0, 27)	1
  (0, 8)	1
  (0, 33)	1
  (0, 1)	1
  (1, 5)	1
  (1, 16)	2
  (1, 15)	2
  (1, 0)	1
  (1, 14)	1
  (1, 6)	1
  (1, 34)	1
  (1, 23)	1
  (1, 3)	1
  (2, 13)	1
  (2, 24)	1
  (2, 15)	1
  (2, 14)	1
  (2, 7)	1
  (2, 30)	1
  (2, 20)	2
  (2, 19)	2
  (2, 4)	1
  (2, 22)	1
  (2, 31)	1
  (2, 12)	1
  (2, 28)	1
  (3, 18)	1
  (3, 13)	1
  (3, 24)	1
  (3, 29)	1
  (3, 2)	2
  (3, 16)	1
  (3, 15)	1
  (3, 30)	1
  (3, 31)	1
  (3, 32)	1
  (3, 25)	1
  (3, 17)	1
  (3, 9)	1
  (3, 26)	1

## 9. Inspect CountVectorizer Vocabulary

The vectorizer creates a vocabulary containing the unique words found in our documents.

Each vocabulary word becomes a feature or column in the numerical representation.

In [10]:
vocabulary = count_vectorizer.get_feature_names_out()

print(vocabulary)

['allow' 'assistant' 'chatbot' 'classification' 'complex' 'computer'
 'datum' 'deep' 'engine' 'generate' 'help' 'human' 'image' 'language'
 'learn' 'learning' 'machine' 'modern' 'natural' 'network' 'neural' 'nlp'
 'pattern' 'prediction' 'processing' 'question' 'response' 'search'
 'speech' 'understand' 'use' 'useful' 'user' 'virtual' 'widely']

## 10. CountVectorizer Matrix

Each row represents a document.

Each column represents a vocabulary word.

Each value represents the number of times that word appears in the document.

In [11]:
count_df = pd.DataFrame(
    count_matrix.toarray(),
    columns=count_vectorizer.get_feature_names_out()
)

count_df

,allow,assistant,chatbot,classification,complex,computer,datum,deep,engine,generate,...,question,response,search,speech,understand,use,useful,user,virtual,widely
0,0,1,1,0,0,1,0,0,1,0,...,0,0,1,0,1,0,0,0,1,0
1,1,0,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,1,1,0,0,0
3,0,0,2,0,0,0,0,0,0,1,...,1,1,0,0,1,1,1,1,0,0

## 11. TfidfVectorizer

TF-IDF stands for:

**Term Frequency — Inverse Document Frequency**

TF-IDF gives higher importance to words that are:

- frequent in a particular document
- relatively rare across the collection of documents

Words appearing in many documents generally receive lower importance.

### Main idea

Frequent in one document + Rare across documents = Higher TF-IDF score

In [12]:
tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(
    cleaned_documents
)

print(tfidf_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 49 stored elements and shape (4, 35)>
  Coords	Values
  (0, 18)	0.2322534644539482
  (0, 13)	0.37605839197923396
  (0, 24)	0.18802919598961698
  (0, 10)	0.29458407004599485
  (0, 5)	0.2322534644539482
  (0, 29)	0.2322534644539482
  (0, 11)	0.29458407004599485
  (0, 21)	0.29458407004599485
  (0, 2)	0.2322534644539482
  (0, 27)	0.29458407004599485
  (0, 8)	0.29458407004599485
  (0, 33)	0.29458407004599485
  (0, 1)	0.29458407004599485
  (1, 5)	0.24495701853416751
  (1, 16)	0.48991403706833503
  (1, 15)	0.39662763571930204
  (1, 0)	0.31069691759295764
  (1, 14)	0.24495701853416751
  (1, 6)	0.31069691759295764
  (1, 34)	0.31069691759295764
  (1, 23)	0.31069691759295764
  (1, 3)	0.31069691759295764
  (2, 13)	0.15913964224551425
  (2, 24)	0.15913964224551425
  (2, 15)	0.15913964224551425
  (2, 14)	0.19656911815718003
  (2, 7)	0.24932300152437956
  (2, 30)	0.19656911815718003
  (2, 20)	0.4986460030487591
  (2, 19)	0.4986460030487591
  (2, 4)	0.24932300152437956
  (2, 22)	0.24932300152437956
  (2, 31)	0.19656911815718003
  (2, 12)	0.24932300152437956
  (2, 28)	0.24932300152437956
  (3, 18)	0.22935452703166073
  (3, 13)	0.18568225630448254
  (3, 24)	0.18568225630448254
  (3, 29)	0.22935452703166073
  (3, 2)	0.45870905406332146
  (3, 16)	0.22935452703166073
  (3, 15)	0.18568225630448254
  (3, 30)	0.22935452703166073
  (3, 31)	0.22935452703166073
  (3, 32)	0.29090713550952246
  (3, 25)	0.29090713550952246
  (3, 17)	0.29090713550952246
  (3, 9)	0.29090713550952246
  (3, 26)	0.29090713550952246

## 12. Inspect the TF-IDF Matrix

The TF-IDF vectorizer converts each document into a numerical vector.

Each value represents the importance of a particular word in that document.

A higher TF-IDF value generally means that the word is more useful for distinguishing that document from the others.

In [13]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vectorizer.get_feature_names_out()
)

tfidf_df

,allow,assistant,chatbot,classification,complex,computer,datum,deep,engine,generate,...,question,response,search,speech,understand,use,useful,user,virtual,widely
0,0.000000,0.294584,0.232253,0.000000,0.000000,0.232253,0.000000,0.000000,0.294584,0.000000,...,0.000000,0.000000,0.294584,0.000000,0.232253,0.000000,0.000000,0.000000,0.294584,0.000000
1,0.310697,0.000000,0.000000,0.310697,0.000000,0.244957,0.310697,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.310697
2,0.000000,0.000000,0.000000,0.000000,0.249323,0.000000,0.000000,0.249323,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.249323,0.000000,0.196569,0.196569,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.458709,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.290907,...,0.290907,0.290907,0.000000,0.000000,0.229355,0.229355,0.229355,0.290907,0.000000,0.000000

## 13. Inspect Top TF-IDF Terms

We will identify the words with the highest TF-IDF scores for each document.

This helps us understand which words are most important or representative of each document.

In [14]:
def get_top_tfidf_terms(
    tfidf_matrix,
    vectorizer,
    top_n=5
):
    feature_names = vectorizer.get_feature_names_out()

    results = []

    for document_index in range(tfidf_matrix.shape[0]):

        scores = tfidf_matrix[
            document_index
        ].toarray().flatten()

        top_indices = scores.argsort()[::-1][:top_n]

        terms = [
            (
                feature_names[index],
                scores[index]
            )
            for index in top_indices
            if scores[index] > 0
        ]

        results.append(terms)

    return results

In [15]:
top_terms = get_top_tfidf_terms(
    tfidf_matrix,
    tfidf_vectorizer,
    top_n=5
)

for document_number, terms in enumerate(
    top_terms,
    start=1
):

    print(f"\nDocument {document_number}")

    for term, score in terms:
        print(f"{term:20} {score:.4f}")

Document 1
language             0.3761
search               0.2946
virtual              0.2946
human                0.2946
help                 0.2946

Document 2
machine              0.4899
learning             0.3966
widely               0.3107
datum                0.3107
classification       0.3107

Document 3
network              0.4986
neural               0.4986
speech               0.2493
deep                 0.2493
complex              0.2493

Document 4
chatbot              0.4587
question             0.2909
user                 0.2909
generate             0.2909
response             0.2909

## 14. Reusable Text → Vector Function

In a real NLP or machine learning application, we need to convert new text into the same numerical representation used during training.

The process is:

Raw Text
↓
Preprocessing
↓
Clean Text
↓
Fitted Vectorizer
↓
Numerical Vector

The vectorizer must already be fitted on the training documents.

For new text, we use:

`vectorizer.transform()`

We should not fit the vectorizer again on new text.

In [16]:
def text_to_vector(
    text: str,
    vectorizer
):
    """
    Convert raw text into a numerical vector.

    The vectorizer must already be fitted.
    """

    cleaned_text = preprocess_to_string(text)

    vector = vectorizer.transform(
        [cleaned_text]
    )

    return vector

## 15. Test the Text → Vector Function

We will provide a new sentence to our reusable function.

The new sentence will:

1. Be preprocessed.
2. Be converted using the vocabulary learned by the vectorizer.
3. Be transformed into a numerical TF-IDF vector.

The vectorizer will not be fitted again.

In [17]:
new_text = """
Natural language processing is used to build intelligent chatbots.
"""

new_vector = text_to_vector(
    new_text,
    tfidf_vectorizer
)

print(new_vector.toarray())

[[0.         0.         0.54957835 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.44493104 0.         0.         0.         0.
  0.54957835 0.         0.         0.         0.         0.
  0.44493104 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]]

## 16. Inspect the New Text Vector

The new text vector has the same number of features as the vocabulary learned by the TF-IDF vectorizer.

This is important because machine learning models require training data and new data to use the same feature structure.

In [18]:
print("Vector shape:", new_vector.shape)

print(
    "Number of features:",
    len(tfidf_vectorizer.get_feature_names_out())
)

Vector shape: (1, 35)
Number of features: 35

## 17. Training Data vs New Data

For training data, we use:

`vectorizer.fit_transform(training_documents)`

This learns the vocabulary and transforms the documents.

For new data, we use:

`vectorizer.transform(new_documents)`

We do not fit the vectorizer again on new data.

This ensures that both training data and new data use the same vocabulary and feature space.

In [19]:
training_vectors = tfidf_vectorizer.fit_transform(
    cleaned_documents
)

new_text_vector = tfidf_vectorizer.transform(
    [preprocess_to_string(new_text)]
)

print("Training vector shape:", training_vectors.shape)
print("New text vector shape:", new_text_vector.shape)

Training vector shape: (4, 35)
New text vector shape: (1, 35)

## 18. Summary

Today we learned the basic NLP preprocessing and text vectorization pipeline.

### Text Preprocessing

- Tokenization breaks text into individual tokens.
- Stop-word removal removes common words.
- Lemmatization converts words into their base forms.
- spaCy provides a convenient reusable preprocessing pipeline.

### Text Vectorization

- `CountVectorizer` represents text using word counts.
- `TfidfVectorizer` represents text using TF-IDF scores.
- TF-IDF helps identify important words in documents.

### Reusable Functions

We created:

- `preprocess_text()`
- `preprocess_to_string()`
- `text_to_vector()`
- `get_top_tfidf_terms()`

### Final Pipeline

Raw Text
↓
Tokenization
↓
Stop-word Removal
↓
Lemmatization
↓
Clean Text
↓
Vectorization
↓
Numerical Vector
↓
Machine Learning Model